version: '3.6'

services:
    db:
        image: mysql
        hostname: db
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: security
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        ports:
            - "32000:3306"
        networks:
            - main_net

    # app:
    #     container_name: app
    #     depends_on:
    #         - db
    #     build: ./security
    #     restart: always
    #     networks:
    #         - main_net

networks:
    main_net:
        name: main_net